global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - 'rules.yml'

# TODO: make target configurable
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

# TODO: make targets configurable
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'substrate_node'
    scrape_interval: 5s
    static_configs:
      - targets: ['3.21.241.151:9615']
  - job_name: "node_exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["3.21.241.151:9100"]
  - job_name: "process-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["3.21.241.151:9256"]